name: Dependabot Auto-Merge
on:
  workflow_run:
    types:
      - completed
    workflows:
      # List all required workflow names here.
      - 'Build App'
      - 'CodeQL'
      - 'Fixup-check'
      - 'i18n Extract'
      - 'Standard Lint'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success' &&
            (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_MERGE }}
          PRESET: DEPENDABOT_MINOR
          MERGE_METHOD: MERGE