name: Dependabot Auto-Merge
on: pull_request_target

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        if: github.ref == 'refs/heads/main' &&
            (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          target: minor
          github-token: ${{ secrets.DEPENDABOT_MERGE }}
