name: Dependabot Auto-Merge
on:
  check_suite:
    types:
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: ridedott/merge-me-action@v2
        # if: github.ref == 'refs/heads/main' &&
        #     (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')
        with:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_MERGE }}
          PRESET: DEPENDABOT_MINOR