name: i18n Extract

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Block on unextracted Changes (Node ${{ matrix.node }})

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Extract i18n
        run: npm run i18n:extract

      - name: Check for changes
        run: |
          bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Unextracted changes on translations' && git status && exit 1 )"
