name: Standard Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']
    name: Block on linting errors (Node ${{ matrix.node }})

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run standard lint
        run: npm run lint
